- README.md
GitHub re-writes them to be relative to `/llogiq/bytecount/blob/master/`.
> Make README links absolute

- Cargo.toml
- src/lib.rs
- tests/check.rs
This is roughly ~10% slower with `target-cpu=native`, ~20% slower without, but has only one line of `unsafe`:
let mid = &x[d1..d2];
assert!(mid.len() % align == 0);
let mid = unsafe {
slice::from_raw_parts(mid.as_ptr() as *const [usize; 4], mid.len() / align)
};
and is significantly shorter.
This should be *much* easier to audit for safety, and significantly easier to audit over all.
**New**
test bench_1000000_hyper ... bench:      42,402 ns/iter (+/- 41,628)
test bench_100000_hyper  ... bench:       4,437 ns/iter (+/- 1,522)
test bench_10000_hyper   ... bench:         417 ns/iter (+/- 68)
test bench_1000_hyper    ... bench:          58 ns/iter (+/- 7)
test bench_100_hyper     ... bench:          18 ns/iter (+/- 4)
test bench_10_hyper      ... bench:           9 ns/iter (+/- 2)
test …
> Safer version, roughly (but not quite) as fast

- Cargo.toml
- benches/bench.rs
- src/bench.rs
There is one small hitch: it seems to search in SRC/ instead of benches/ cc @bluss
@Veedrac think we should merge this?
> convert benchmarks to bluss' bencher

- benches/bench.rs
- src/lib.rs
- tests/check.rs
For a one-liner this code sure is getting long.
I worked out the performance issue I was having - LLVM was getting really confused by a by-value `sum` taking a `[T; 4]`. Changing that to a reference fixed things.
I've tuned the specific constants for my machine. Verification that I haven't caused a regression would be helpful. When doing so you might notice there are a *lot* more benchmarks. This is getting unwieldy, but they've been very useful for me.
Fixes #10.
> Specialized algorithm for different ranges of values.

- Cargo.toml
- src/lib.rs
Clippy suggested replacing indexed loops with iterators. Benchmarking on my machine shows slightly faster execution with iterators, so let's take the suggestion. Thanks clippy! cc @Veedrac
Also I found that `haystack.iter().filter(|&&c| c == needle).count()` is a bit faster than the fold variant in our benches; but before changing that I'd like to make sure we have more realistic benchmarks w.r.t. branch misses.
> fixed some clippy warnings

- src/lib.rs
None of this should really change anything, but in principle it could allow the compiler to optimize slightly better.  :)
More to the point, it makes better use of the standard library’s facilities for slice manipulation, which I feel makes the code clearer.  In addition, it uses the named constant `usize::MAX` in place of the `max_value` method, which makes it clearer that the value in question really is a compile-time constant.
> Some minor style cleanup

- Cargo.toml
- README.md
- benches/bench.rs
- src/lib.rs
This can be faster if we get predominantly small slices. We also may want to limit the count size to usize (which means 16 for 16-bit machines).
> new variant: naive with 32bit count

- Cargo.toml
- benches/bench.rs
- src/lib.rs
This fixes #26 and improves crates.io display. Also gets rid of the remaining clippy warnings. WIll publish once CI is successful.
> make bytecount no-std, add categories/badges

- .gitignore
- .travis.yml
- Cargo.toml
- appveyor.yml
- benches/bench.rs
This is a simple conversion of our benchmarks to use [criterion](https://crates.io/crates/criterion). I really like the method of benchmarking over a slice of values, and the produced graphs are nice, too.
I marked this as experimental, as the current version crashed on me a few times. Github master appears to be more stable, so I'd like to wait for the next release to merge.
> [Experimental] Convert benchmarks to criterion

- src/lib.rs
Based on discussion in https://github.com/rust-lang/rust/pull/52972:
References have to be always aligned. This includes `&[T]`, and it includes the case where the slice is empty. `chunk_align` was producing an unaligned `mid` part when the `cmp::min(..., d2)` picked the RHS.
So I pulled the conditional out of `cmp::min`, returning early if the slice is so short that the aligned beginning is beyond the end of the slice.
> Make sure we do not create an unaligned slice

- .travis.yml
- Cargo.toml
- appveyor.yml
- src/integer_simd.rs
- src/lib.rs
- src/naive.rs
- src/simd/generic.rs
- src/simd/mod.rs
- src/simd/x86_avx2.rs
- src/simd/x86_sse2.rs
Sigh. I'm not a fan of Rust's fragmentation around SIMD. Let's see, we have
1. An AVX2 implementation, using Intel's intrinsics,
2. An SSE2 implementation, using Intel's intrinsics,
3. A generic version, using `packed_simd`,
4. A fake-integer-SIMD version, using bit magic,
5. A trivial fallback.
Why? Well,
1. the AVX2 implementation exists because it's the fastest,
2. the SSE2 implementation exists because the generic version requires nightly,
3. the generic version exists because other architectures exist, plus it's strictly better than the SSE2 version, plus it works with `no_std`,
4. the fake-integer-SIMD version exists for the same reason the generic one does, though it isn't as good as any of the above, but doesn't require nightly,
5. the fallback version exists for short vectors and …
> Fancy new algorithm on stable SIMD and a bunch of other stuff

- .travis.yml
- ci/miri.sh
- tests/check.rs
A long time ago, I think at RustFest Rome, we talked about using Miri to test bytecount. Back then Miri wasn't up for the task, but these days it is. :)
In the default settings, each quickcheck test takes around 50s in Miri on my machine, which seems okay. When running the tests locally, one can make things go faster with something like
```
QUICKCHECK_TESTS=10 cargo miri test -- -Zmiri-disable-isolation
```
("disable-isolation" is needed to forward the env var to the program)
Note that by default Miri makes all RNGs deterministic. We could add the `-Zmiri-disable-isolation` flag to allow seeing from the OS RNG.
Also fixes https://github.com/llogiq/bytecount/issues/53.
> add Miri CI

- Cargo.toml
- src/integer_simd.rs
- src/simd/generic.rs
- src/simd/x86_avx2.rs
This updates the packed_simd dependency to packed_simd_2 (more on that at https://github.com/rust-lang/packed_simd/issues/298). It fixes compilation in the 0.3.4 update on recent nightly toolchains. While I was at it, I fixed some clippy lints.
> Use packed_simd_2

- tests/check.rs
This was introduced in Rust 1.26, and the minimum version of v0.6 of this crate is 1.32. The change makes the test behaviour more obvious.
> Use inclusive range instead of chaining 255 to range.

- src/simd/generic.rs
- tests/check.rs
It's a simple overflow, because the generic SIMD code uses 512 bit vectors in some of the loops, which none of the other code does.
> Fixed overflow bug

- Cargo.toml
packed_simd is apparently being published under its original name again.
> Switch back to packed_simd dependency

- src/simd/x86_sse2.rs
This replaces SSE4.1 `_mm_extract_epi32` with SSE2 `_mm_cvtsi128_si32` and `_mm_shuffle_epi32`.
Should fix #85 and doesn't appear to break anything else.
> Avoid use of SSE4.1 intrinsic for SSE2

- .github/workflows/ci.yml
- src/integer_simd.rs
- src/lib.rs
- src/naive.rs
- src/simd/aarch64.rs
- src/simd/generic.rs
- src/simd/mod.rs
- src/simd/x86_avx2.rs
- tests/check.rs
I'm still without a good ARM CPU (but will hopefully get one, soon), but here's what I think should likely be the aarch64 intrinsics version of bytecount.
@Veedrac if you have a bit of time, I'd appreciate a review.
> Add aarch64 SIMD specialization

- Cargo.toml
- README.md
- src/lib.rs
- src/simd/generic.rs
Fixes #91
As mentioned in the `packed_simd` README, [the crate is superseded by `#![feature(portable_simd)]`](https://github.com/rust-lang/packed_simd#:~:text=will%20be%20superseded%20by%20%23!%5Bfeature(portable_simd)%5D.).
I'm honestly not familiar with simd or the new `std::simd` support, but I think I managed to get things working without the use of `packed_simd` (at least from local testing).
> remove `packed_simd` in favor of `std::simd` and `#![feature(portable_simd)]`

- src/lib.rs
Do this by avoiding trying to use neon / SIMD on big-endian aarch64. Neon intrinsics are problematical on big-endian targets, ref. https://github.com/rust-lang/stdarch/issues/1484
> src/lib.rs: make this build on big-endian aarch64.

- src/simd/wasm.rs
The loop condition was incorrect which meant it would read beyond the end of `haystack` and crash if it went beyond the end of memory. It would probably give incorrect counts too.
Fixes #97
> Fix WASM chunk_count
